import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/sass/custom.scss';
import '@/styles/css/global.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import Header from '@/components/layout/header';
import BoostrapClient from '@/components/bootstrap-client';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <BoostrapClient />
                <Header />
                {children}
            </body>
        </html>
    );
}
